# Generated by Django 2.2.1 on 2019-07-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190723_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('can_view_expert_contact_info', '查看专家联系方式'), ('can_change_expert_contact_info', '修改专家联系方式'), ('can_delete_expert_workexp', '删除专家工作经历'), ('can_delete_expert_comments', '删除专家评论'), ('can_add_project_interview', '修改项目访谈'), ('can_delete_project_interview', '删除项目访谈'), ('can_change_project_interview', '修改项目访谈'), ('can_view_project_interview', '查看项目访谈'), ('can_change_all_project_interview', '修改所有项目访谈'), ('can_view_all_project_interview', '查看所有项目访谈'), ('can_add_client', '新增客户'), ('can_view_client_info', '查看客户信息'), ('can_change_client_info', '修改客户信息'), ('can_delete_client_info', '删除客户信息'), ('can_view_client_cfee', '查看客户资费'), ('can_delete_client_cfee', '修改客户资费'), ('can_add_client_bc_fc', '新增客户联系人'), ('can_view_client_bc_fc_contact', '查看客户联系人联系方式'), ('can_change_client_bc_fc_contact', '修改客户联系人联系方式'), ('can_delete_client_bc_fc_contact', '删除客户联系人联系方式'))},
        ),
    ]
