# Generated by Django 2.2.1 on 2019-08-02 15:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_auto_20190802_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUserModel',
            new_name='MyUser',
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='users_myuser',
        ),
    ]
