# Generated by Django 2.2.1 on 2019-07-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '0008_payment'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目名称')),
                ('cname', models.CharField(blank=True, max_length=150, null=True, verbose_name='客户名称')),
                ('pm', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目经理')),
                ('pm_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('pm_email', models.CharField(blank=True, max_length=150, null=True)),
                ('pm_gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('X', '未知')], default='X', max_length=10)),
                ('pcreatetime', models.DateField(auto_now_add=True)),
                ('pdeadline', models.CharField(blank=True, max_length=50, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
            options={
                'db_table': 'project_info',
                'ordering': ('-pcreatetime',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project2Expert',
            fields=[
                ('pteid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(blank=True, max_length=150, null=True, verbose_name='项目名称')),
                ('ename', models.CharField(blank=True, max_length=50, null=True, verbose_name='专家姓名')),
                ('ecompany', models.CharField(blank=True, max_length=150, null=True, verbose_name='专家公司')),
                ('status', models.IntegerField(choices=[(1, '已访谈'), (0, '未访谈')], default=0, verbose_name='访谈状态')),
                ('itv_stime', models.CharField(blank=True, max_length=50, null=True, verbose_name='访谈时间')),
                ('itv_duration', models.IntegerField(blank=True, default=0, verbose_name='访谈时常')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.ExpertInfo')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'db_table': 'p_e_relationship',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='expertinfos',
            field=models.ManyToManyField(through='projects.Project2Expert', to='experts.ExpertInfo'),
        ),
    ]
