# Generated by Django 2.2.1 on 2019-07-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0011_auto_20190715_1449'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True, 'ordering': ('-pcreatetime', 'pdeadline')},
        ),
        migrations.AlterUniqueTogether(
            name='project2expert',
            unique_together={('pid', 'eid')},
        ),
    ]
