# Generated by Django 2.2.1 on 2019-07-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190717_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='premark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
