# Generated by Django 2.2.1 on 2019-07-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_premark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pm_gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('X', '未知')], default='X', max_length=50),
        ),
    ]
