# Generated by Django 2.2.1 on 2019-07-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190718_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='project2expert',
            name='c_payment',
            field=models.FloatField(blank=True, default=0.0, verbose_name='客户收费'),
        ),
        migrations.AddField(
            model_name='project2expert',
            name='e_payment',
            field=models.FloatField(blank=True, default=0.0, verbose_name='专家付费'),
        ),
        migrations.AddField(
            model_name='project2expert',
            name='fee_index',
            field=models.FloatField(blank=True, default=0.0, verbose_name='咨费系数'),
        ),
        migrations.AddField(
            model_name='project2expert',
            name='interviewer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='约谈人'),
        ),
        migrations.AddField(
            model_name='project2expert',
            name='itv_etime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='访谈时间'),
        ),
        migrations.AddField(
            model_name='project2expert',
            name='recorder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='录入人'),
        ),
        migrations.AlterUniqueTogether(
            name='project2expert',
            unique_together=set(),
        ),
    ]
