# Generated by Django 2.2.1 on 2019-07-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190724_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project2expert',
            options={'managed': True, 'ordering': ('-itv_date', '-itv_stime')},
        ),
        migrations.RemoveField(
            model_name='project',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pm_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pm_gender',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pm_mobile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pm_wechat',
        ),
        migrations.RemoveField(
            model_name='project2expert',
            name='ecompany',
        ),
        migrations.RemoveField(
            model_name='project2expert',
            name='ename',
        ),
        migrations.RemoveField(
            model_name='project2expert',
            name='pname',
        ),
        migrations.AddField(
            model_name='project2expert',
            name='itv_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='访谈日期'),
        ),
        migrations.AddField(
            model_name='project2expert',
            name='itv_paid_duration',
            field=models.IntegerField(blank=True, default=0, verbose_name='计费时长'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project2expert',
            name='c_payment',
            field=models.FloatField(blank=True, default=0.0, verbose_name='客户收费总额'),
        ),
        migrations.AlterField(
            model_name='project2expert',
            name='e_payment',
            field=models.FloatField(blank=True, default=0.0, verbose_name='专家付费总额'),
        ),
        migrations.AlterField(
            model_name='project2expert',
            name='itv_etime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='project2expert',
            name='itv_stime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='开始时间'),
        ),
    ]
