# Generated by Django 2.2.1 on 2019-07-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190725_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pcreatetime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
