# Generated by Django 2.2.1 on 2019-08-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190730_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pcreatetime',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdeadline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='我方项目对接人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pm',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='项目经理'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pname',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project2expert',
            name='interviewer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='约谈人'),
        ),
        migrations.AlterField(
            model_name='project2expert',
            name='itv_date',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='访谈日期'),
        ),
        migrations.AlterField(
            model_name='project2expert',
            name='itv_etime',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='project2expert',
            name='itv_stime',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='project2expert',
            name='recorder',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='录入人'),
        ),
    ]
