# Generated by Django 2.2.1 on 2019-08-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190806_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='project2expert',
            name='avg_score',
            field=models.FloatField(blank=True, default=0.0, verbose_name='均分'),
        ),
        migrations.AddField(
            model_name='project2expert',
            name='communication',
            field=models.IntegerField(blank=True, default=0, verbose_name='沟通能力'),
        ),
        migrations.AddField(
            model_name='project2expert',
            name='cooperation',
            field=models.IntegerField(blank=True, default=0, verbose_name='配合程度'),
        ),
        migrations.AddField(
            model_name='project2expert',
            name='knowledge',
            field=models.IntegerField(blank=True, default=0, verbose_name='知识范围'),
        ),
    ]
