# Generated by Django 2.2.1 on 2019-08-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project2expert_itv_approach'),
    ]

    operations = [
        migrations.AddField(
            model_name='project2expert',
            name='itv_remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
