# Generated by Django 2.2.1 on 2019-07-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(blank=True, max_length=150, null=True, verbose_name='客户名称')),
                ('bc_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='主业务联系人')),
                ('fc_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='主财务联系人')),
                ('half_hrs', models.IntegerField(choices=[(1, '可半小时'), (0, '不可半小时'), (2, '未知')], default=2, verbose_name='是否支持半小时访谈')),
                ('ctype', models.CharField(blank=True, max_length=50, null=True, verbose_name='客户类型')),
                ('cinfo', models.TextField(blank=True, null=True, verbose_name='客户介绍')),
            ],
            options={
                'db_table': 'client_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinancialContact',
            fields=[
                ('fc_id', models.AutoField(primary_key=True, serialize=False)),
                ('fc_name', models.CharField(blank=True, max_length=50, null=True)),
                ('fc_gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('X', '未知')], default='X', max_length=10)),
                ('fc_mobile', models.CharField(blank=True, max_length=150, null=True)),
                ('fc_email', models.CharField(blank=True, max_length=150, null=True)),
                ('pc_position', models.CharField(blank=True, max_length=80, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
            options={
                'db_table': 'client_financial_contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('bc_id', models.AutoField(primary_key=True, serialize=False)),
                ('bc_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bc_gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('X', '未知')], default='X', max_length=10)),
                ('bc_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('bc_email', models.CharField(blank=True, max_length=150, null=True)),
                ('bc_position', models.CharField(blank=True, max_length=80, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
            options={
                'db_table': 'client_business_contact',
                'managed': True,
            },
        ),
    ]
