# Generated by Django 2.2.1 on 2019-07-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True, 'ordering': ('-cid',)},
        ),
    ]
