# Generated by Django 2.2.1 on 2019-07-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20190716_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='bc_id',
            new_name='bc_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='fc_id',
            new_name='fc_name',
        ),
    ]
