# Generated by Django 2.2.1 on 2019-07-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20190716_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='half_hrs',
        ),
        migrations.AddField(
            model_name='client',
            name='cpolicy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='收费政策'),
        ),
        migrations.AddField(
            model_name='client',
            name='cremark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
