# Generated by Django 2.2.1 on 2019-07-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_cfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='bc_wechat',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='financialcontact',
            name='fc_wechat',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
