# Generated by Django 2.2.1 on 2019-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20190725_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpolicy',
            field=models.TextField(blank=True, null=True, verbose_name='收费政策'),
        ),
    ]
