# Generated by Django 2.2.1 on 2019-08-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20190802_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontact',
            name='bc_mobile',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='businesscontact',
            name='bc_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='businesscontact',
            name='bc_position',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='bc_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='主业务联系人'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ctype',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='客户类型'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fc_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='主财务联系人'),
        ),
        migrations.AlterField(
            model_name='financialcontact',
            name='fc_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='financialcontact',
            name='fc_position',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
