# Generated by Django 2.2.1 on 2019-07-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertinfo',
            name='eadded_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expertinfo',
            name='eupdated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
