# Generated by Django 2.2.1 on 2019-07-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0009_auto_20190715_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertinfo',
            name='eadded_by',
        ),
    ]
