# Generated by Django 2.2.1 on 2019-07-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0010_remove_expertinfo_eadded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertinfo',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='expertinfo',
            name='ebirthday',
        ),
        migrations.RemoveField(
            model_name='expertinfo',
            name='elandline',
        ),
        migrations.RemoveField(
            model_name='expertinfo',
            name='emsn',
        ),
        migrations.RemoveField(
            model_name='expertinfo',
            name='ephoto',
        ),
    ]
