# Generated by Django 2.2.1 on 2019-07-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0011_auto_20190715_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertinfo',
            name='interview_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
