# Generated by Django 2.2.1 on 2019-07-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0012_expertinfo_interview_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertinfo',
            name='ename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expertinfo',
            name='esex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
