# Generated by Django 2.2.1 on 2019-07-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0013_auto_20190718_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertinfo',
            name='interview_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
