# Generated by Django 2.2.1 on 2019-07-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0014_auto_20190724_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexp',
            name='istonow',
        ),
        migrations.AlterField(
            model_name='expertinfo',
            name='efee',
            field=models.FloatField(blank=True, default=0.0, verbose_name='专家付费单价'),
        ),
        migrations.AlterField(
            model_name='expertinfo',
            name='esex',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('X', '未知')], default='X', max_length=10),
        ),
    ]
